import type { HybridObject } from 'react-native-nitro-modules';

export interface PioneerClient extends HybridObject<{ ios: 'c++'; android: 'c++' }> {
    versionJson(): string;
    initializeJson(configJson: string): string;
    clientScopeAcquireJson(inputJson: string): string;
    clientScopeReleaseJson(inputJson: string): string;
    clientShutdownJson(): Promise<string>;
    clientIntentDispatchJson(inputJson: string): string;
    clientScopedSnapshotJson(inputJson: string): string;
    clientChangeBatchJson(inputJson: string): string;
    clientWaitPublicationsJson(inputJson: string): Promise<string>;
    clientEffectCompleteJson(inputJson: string): string;
    clientEffectCancelJson(inputJson: string): string;
    clientSequenceGapResnapshotJson(inputJson: string): string;
    mobileStartupRecordJson(inputJson: string): string;
    diagnosticsDrainJson(): string;
    gatewayLoadRegistryV3Json(inputJson: string): string;
    gatewaySessionValidateJson(inputJson: string): Promise<string>;
    gatewayDeviceActivationPresentationJson(inputJson: string): Promise<string>;
    gatewayDeviceActivationParseJson(inputJson: string): Promise<string>;
    gatewayAuthMeJson(inputJson: string): Promise<string>;
    gatewayAuthorizationCapabilitiesJson(inputJson: string): Promise<string>;
    invitationPresentationJson(inputJson: string): Promise<string>;
    invitationCreateJson(inputJson: string): Promise<string>;
    memberAvatarCacheJson(inputJson: string): Promise<string>;
    agentAvatarCacheJson(inputJson: string): Promise<string>;
    memberDeviceCreateJson(inputJson: string): Promise<string>;
    gatewayTransportReserveJson(inputJson: string): string;
    gatewayTransportWaitJson(inputJson: string): Promise<string>;
    gatewayTransportReleaseJson(inputJson: string): string;
    artifactViewOpenJson(inputJson: string): Promise<string>;
    threadFileViewOpenJson(inputJson: string): Promise<string>;
    artifactDownloadJson(inputJson: string): Promise<string>;
    workspaceBootstrapJson(inputJson: string): Promise<string>;
    workspaceSwitchJson(inputJson: string): Promise<string>;
    workspaceCreateJson(inputJson: string): Promise<string>;
    workspaceRenameJson(inputJson: string): Promise<string>;
    composerVoiceCapturePlanJson(inputJson: string): Promise<string>;
    voiceSessionStartJson(inputJson: string): Promise<string>;
    voiceAudioChunkJson(inputJson: string, pcmChunk: ArrayBuffer): string;
    voiceSessionFinalizeJson(inputJson: string): Promise<string>;
    voiceSessionCancelJson(inputJson: string): Promise<string>;
    pendingRequestPresentationJson(inputJson: string): string;
    principalPresentationCapabilitiesJson(inputJson: string): string;
    artifactPresentationPolicyJson(inputJson: string): string;
    currentPrincipalPresentationJson(inputJson: string): string;
    sessionListRowPresentationJson(inputJson: string): string;
    threadCreateVisibilityPlanJson(inputJson: string): string;
    memberPresentationJson(inputJson: string): string;
    composerAttachmentFromPathJson(inputJson: string): string;
    composerSkillPackPickerJson(inputJson: string): string;
    composerSkillChipsJson(inputJson: string): string;
    composerCapabilityTargetJson(inputJson: string): string;
    composerCapabilityMenuVisibilityJson(inputJson: string): string;
    composerSubmissionPlanJson(inputJson: string): string;
    composerSkillRowsForTargetJson(inputJson: string): string;
    composerFilterMcpRowsJson(inputJson: string): string;
    threadTreeRefreshJson(inputJson: string): Promise<string>;
    threadTreeLevelJson(inputJson: string): string;
    activeThreadOpenJson(inputJson: string): Promise<string>;
    activeThreadOpenByIdJson(inputJson: string): Promise<string>;
    activeThreadOpenOrCreateNewJson(inputJson: string): Promise<string>;
    activeThreadSendTextJson(inputJson: string): Promise<string>;
    prepareVoiceComposerSnapshotJson(inputJson: string): Promise<string>;
    activeThreadClearJson(): Promise<string>;
}
