import type { HybridObject } from 'react-native-nitro-modules';

export interface PioneerClient extends HybridObject<{ ios: 'c++'; android: 'c++' }> {
    versionJson(): string;
    initializeJson(configJson: string): string;
    diagnosticsDrainJson(): string;
    gatewayValidateRemoteJson(inputJson: string): Promise<string>;
    gatewayPlanAddRemoteJson(inputJson: string): Promise<string>;
    gatewayPlanAddAndActivateRemoteRegistryJson(inputJson: string): Promise<string>;
    gatewayPlanActivateRegistryJson(inputJson: string): Promise<string>;
    gatewayPlanUpdateRemoteRegistryJson(inputJson: string): Promise<string>;
    gatewayPlanDeleteRemoteRegistryJson(inputJson: string): Promise<string>;
    gatewayPlanSetWorkspaceRegistryJson(inputJson: string): Promise<string>;
    gatewayConnectJson(inputJson: string): Promise<string>;
    gatewaySettingsGetJson(inputJson: string): Promise<string>;
    gatewaySettingsUpdateJson(inputJson: string): Promise<string>;
    gatewayNextEventsJson(): Promise<string>;
    gatewayDisconnectJson(): Promise<string>;
    workspaceBootstrapJson(inputJson: string): Promise<string>;
    workspaceSwitchJson(inputJson: string): Promise<string>;
    workspaceCreateJson(inputJson: string): Promise<string>;
    workspaceRenameJson(inputJson: string): Promise<string>;
    providerListJson(inputJson: string): Promise<string>;
    cliRuntimeListJson(inputJson: string): Promise<string>;
    cliRuntimeRefreshJson(inputJson: string): Promise<string>;
    cliRuntimeListModelsJson(inputJson: string): Promise<string>;
    cliRuntimeThreadBindingGetJson(inputJson: string): Promise<string>;
    cliRuntimeThreadCompactJson(inputJson: string): Promise<string>;
    cliRuntimeTurnSteerJson(inputJson: string): Promise<string>;
    cliRuntimeReviewStartJson(inputJson: string): Promise<string>;
    cliRuntimeRequestRespondJson(inputJson: string): Promise<string>;
    turnPermissionRequestRespondJson(inputJson: string): Promise<string>;
    voiceStatusJson(inputJson: string): Promise<string>;
    voiceSessionStartJson(inputJson: string): Promise<string>;
    voiceAudioChunkJson(inputJson: string, pcmChunk: ArrayBuffer): string;
    voiceSessionFinalizeJson(inputJson: string): Promise<string>;
    voiceSessionCancelJson(inputJson: string): Promise<string>;
    pendingRequestResponsePlanJson(inputJson: string): string;
    pendingRequestPresentationJson(inputJson: string): string;
    providerListModelsJson(inputJson: string): Promise<string>;
    providerListTranscriptionModelsJson(inputJson: string): Promise<string>;
    voiceInputSettingsPlanJson(inputJson: string): string;
    providerModelDisplayJson(inputJson: string): Promise<string>;
    reasoningEffortRowsJson(inputJson: string): string;
    composerPermissionModeOptionsJson(): string;
    composerAttachmentFromPathJson(inputJson: string): string;
    composerAttachmentsUpdateJson(inputJson: string): string;
    composerSkillPickerRowsJson(inputJson: string): Promise<string>;
    composerMcpPickerRowsJson(inputJson: string): Promise<string>;
    composerCapabilitiesUpdateJson(inputJson: string): string;
    composerCapabilityTargetJson(inputJson: string): string;
    composerCapabilityMenuVisibilityJson(inputJson: string): string;
    composerSubmissionPlanJson(inputJson: string): string;
    composerDomainTransitionJson(inputJson: string): string;
    composerDraftLifecycleTransitionJson(inputJson: string): string;
    composerSkillRowsForTargetJson(inputJson: string): string;
    composerSkillCapabilityFromRowJson(inputJson: string): string;
    composerMcpCapabilityFromRowJson(inputJson: string): string;
    composerSkillToggleJson(inputJson: string): string;
    composerMcpToggleJson(inputJson: string): string;
    composerFilterSkillRowsJson(inputJson: string): string;
    composerFilterMcpRowsJson(inputJson: string): string;
    threadTreeRefreshJson(inputJson: string): Promise<string>;
    threadTreeLevelJson(inputJson: string): string;
    threadTimelinePageJson(inputJson: string): Promise<string>;
    turnWorkPageJson(inputJson: string): Promise<string>;
    agentsDocGetJson(inputJson: string): Promise<string>;
    agentsDocSaveJson(inputJson: string): Promise<string>;
    agentsDocArchiveJson(inputJson: string): Promise<string>;
    activeThreadOpenJson(inputJson: string): Promise<string>;
    activeThreadOpenByIdJson(inputJson: string): Promise<string>;
    activeThreadEnsureWorkspaceDraftJson(inputJson: string): Promise<string>;
    activeThreadOpenOrCreateNewJson(inputJson: string): Promise<string>;
    activeThreadSnapshotJson(inputJson: string): string;
    activeThreadApplyEventJson(inputJson: string): Promise<string>;
    activeThreadSendTextJson(inputJson: string): Promise<string>;
    prepareVoiceComposerSnapshotJson(inputJson: string): Promise<string>;
    activeThreadCancelTurnJson(inputJson: string): Promise<string>;
    activeThreadUnsubscribeOrCloseJson(inputJson: string): Promise<string>;
    activeThreadClearJson(): Promise<string>;
}
