#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PioneerClientFfi PioneerClientFfi;

char* pioneer_client_ffi_version(void);
PioneerClientFfi* pioneer_client_ffi_client_create(void);
void pioneer_client_ffi_client_destroy(PioneerClientFfi* client);
char* pioneer_client_ffi_client_initialize(PioneerClientFfi* client, const char* config_json);
char* pioneer_client_ffi_diagnostics_drain(PioneerClientFfi* client);
char* pioneer_client_ffi_gateway_load_registry_v3(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_validate_remote(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_add_remote(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_add_and_activate_remote_registry(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_activate_registry(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_update_remote_registry(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_delete_remote_registry(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_plan_set_workspace_registry(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_session_lifecycle_reduce(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_device_activation_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_device_activation_parse(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_refresh(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_device_activate(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_session_cleanup(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_me(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_profile_update(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_session_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_session_revoke(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_logout(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_auth_device_create(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_preview(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_accept(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_commit_take_refresh(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_commit_secure_storage_committed(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_commit_registry_committed(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_commit_secure_storage_failed(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_commit_registry_failed(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_create(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_revoke(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_avatar_cache(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_agent_avatar_cache(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_suspend(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_restore(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_remove(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_device_create(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_member_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_member_add(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_member_remove(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_participants_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_update(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_participant_add(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_participant_remove(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_session_replace_access(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_settings_get(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_settings_update(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_gateway_next_events(PioneerClientFfi* client);
char* pioneer_client_ffi_gateway_disconnect(PioneerClientFfi* client);
char* pioneer_client_ffi_artifact_view_open(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_artifact_download(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_artifact_download_progress(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_artifact_download_cancel(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_bootstrap(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_switch(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_create(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_workspace_rename(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_provider_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_list(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_refresh(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_list_models(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_thread_binding_get(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_thread_compact(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_turn_steer(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_review_start(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_cli_runtime_request_respond(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_permission_request_respond(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_voice_status(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_voice_session_start(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_voice_audio_chunk(PioneerClientFfi* client, const char* input_json, const uint8_t* pcm_ptr, size_t pcm_len);
char* pioneer_client_ffi_voice_session_finalize(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_voice_session_cancel(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_pending_request_response_plan(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_pending_request_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_provider_list_models(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_provider_list_transcription_models(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_voice_input_settings_plan(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_provider_model_display(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_reasoning_effort_rows(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_permission_mode_options(PioneerClientFfi* client);
char* pioneer_client_ffi_composer_turn_mode_options(PioneerClientFfi* client);
char* pioneer_client_ffi_principal_presentation_capabilities(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_current_principal_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_session_list_row_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_scope_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_create_visibility_plan(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_scope_mutation_plan(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_member_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_invitation_list_row(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_administration_conflict_refetch(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_attachment_from_path(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_attachments_update(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_picker_rows(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_mcp_picker_rows(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_pack_picker(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_selection_toggle(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_chips(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_capabilities_update(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_capability_target(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_capability_menu_visibility(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_submission_plan(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_domain_transition(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_draft_lifecycle_transition(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_rows_for_target(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_capability_from_row(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_mcp_capability_from_row(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_skill_toggle(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_mcp_toggle(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_filter_skill_rows(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_composer_filter_mcp_rows(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_tree_refresh(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_tree_level(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_timeline_page(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_message_edit(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_message_delete(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_message_revisions_page(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_message_revision_page_presentation(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_thread_read(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_work_page(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_turn_work_items_get(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_agents_doc_get(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_agents_doc_save(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_agents_doc_archive(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_open(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_open_by_id(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_ensure_workspace_draft(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_open_or_create_new(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_snapshot(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_apply_event(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_send_text(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_prepare_voice_composer_snapshot(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_cancel_turn(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_unsubscribe_or_close(PioneerClientFfi* client, const char* input_json);
char* pioneer_client_ffi_active_thread_clear(PioneerClientFfi* client);
void pioneer_client_ffi_string_destroy(char* value);

#ifdef __cplusplus
}
#endif
